# Generated by Django 3.0.8 on 2020-07-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobetsu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='admission_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='mail',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
