# Generated by Django 3.0.8 on 2020-07-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobetsu', '0003_participant_choice_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='choice_member',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
